name: Build Template
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: testgen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run cargo generate
        uses: cargo-generate/cargo-generate-action@v0.13.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: template
          template_values_file: .github/workflows/template_values.toml
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo check
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check --tests --all-features --workspace